
(ASDF/PARSE-DEFSYSTEM:DEFSYSTEM :CUP
  :AUTHOR
  "Matt George"
  :MAINTAINER
  "Matt George"
  :LICENSE
  "none"
  :DESCRIPTION
  "Project starter for common lisp"
  :CLASS
  :PACKAGE-INFERRED-SYSTEM
  :DEPENDS-ON
  (:CUP/EXPORTS))
(ASDF/PACKAGE-INFERRED-SYSTEM:REGISTER-SYSTEM-PACKAGES :UNIX-OPTS '(:UNIX-OPTS))
(ASDF/PACKAGE-INFERRED-SYSTEM:REGISTER-SYSTEM-PACKAGES :CL-PPCRE '(:CL-PPCRE))
(ASDF/PACKAGE-INFERRED-SYSTEM:REGISTER-SYSTEM-PACKAGES :ESRAP '(:ESRAP))
